Repository sristy17/MindDrive, pull requests merged in 2024-10, with the labels that each got.

#12 Add Issue Template & PR Templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: good first issue, hacktoberfest-2024, hacktoberfest, up-for-grabs

#11 add signup.ejs and a signup button in sidebar.ejs
  app.js
  controllers/auth.controller.js
  views/includes/sidebar.ejs
  views/pages/index.ejs
  views/pages/profile.ejs
Labels: hacktoberfest-2024, hacktoberfest, hacktoberfest-accepted

#36 feat(git-commit-cli): :sparkles: add Commitizen
  .commitlintrc.cjs
  .github/ISSUE_TEMPLATE/feature_request.yml
  README.md
  package-lock.json
  package.json
Labels: hacktoberfest-2024, hacktoberfest, hacktoberfest-accepted

#34 ui:fixed the inconsistent footer style Fix #31
  public/css/style.css
  views/pages/chatbot.ejs
  views/pages/index.ejs
Labels: hacktoberfest-2024, hacktoberfest, hacktoberfest-accepted

#39 Add Dark Theme Toggle, SEO Enhancements, and Favicon Implementation (#27, #35, #28)
  app.js
  public/css/style.css
  public/images/emojis/happy.png
  public/images/emojis/joyful.png
  public/images/emojis/neutral.png
  public/images/emojis/sad.png
  public/images/favicon.ico
  public/images/greyish-bg.png
  public/js/Profile.js
  public/js/about.js
  public/js/chatbot.js
  public/js/global.js
  routes/auth.routes.js
  routes/gemini.routes.js
  views/includes/sidebar.ejs
  views/pages/about.ejs
  views/pages/chatbot.ejs
  views/pages/index.ejs
  views/pages/profile.ejs
Labels: enhancement, hacktoberfest-2024, hacktoberfest, hacktoberfest-accepted

#43 [FEATURE] Auth Management #33
  app.js
  controllers/auth.controller.js
  package-lock.json
  package.json
  public/js/auth.js
  routes/auth.routes.js
  views/includes/sidebar.ejs
  views/pages/profile.ejs
Labels: hacktoberfest-2024, hacktoberfest, hacktoberfest-accepted

#46 Solved Issue Show User Details when session data is not expired
  app.js
  package-lock.json
  public/js/auth.js
  views/includes/sidebar.ejs
  views/pages/profile.ejs
Labels: hacktoberfest-2024, hacktoberfest, hacktoberfest-accepted
